# -*- coding: utf-8 -*-
"""Hacker Rank - Beginner Case If-Else

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-bEVMxlDTlCiXTwCSb5RypMu08ZqawuO

Task
Given an integer, n , perform the following conditional actions:



*   If n is odd, print Weird
*   If n is even and in the inclusive range of 2 to 5 , print Not Weird
*   If n is even and in the inclusive range of 6 to 20, print Weird
*   If n is even and greater than 20 , print Not Weird

**Input Format**

A single line containing a positive integer, .

**Constraints**

Output Format

Print Weird If n the number is weird. Otherwise, print Not Weird.
"""

import math
import os
import random
import re
import sys

#To ensure the code after the condition being run
if __name__ == '__main__':
  # takes user inputs convert it to an interger
    n = int(input().strip())

"""First Elements

__name__ == '__main__':

This is a common Python construct used to ensure that certain parts of the code are only executed when the script is run directly, and not when it is imported as a module in another script. If the script is being run directly, the block inside this if statement will execute.

Second Elements:

Second Elements

n = int(input().strip())
"""

#Check condition based on the task descriptions

if n % 2 == 1: #if n divided by 2 resulting 1 (odd number) are weird
  print("Weird")
elif n % 2 == 0 and 2 <= n <= 5: #if n can be divided by 2 resulting zero (even number) and range between 2 and 5 is not weird
  print("Not Weird")
elif n % 2 == 0 and 6 <= n <= 20: # similar condition like the above but range between 6 and 20
  print("Weird")
elif n % 2 == 0 and n > 20:
  print("Not Weird")